In [7]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
item 2:
about numpy 

In [ ]:
item 3:
numpy getting started

In [ ]:
item 4:
numpy array

In [9]:
# 0-D array 
import numpy as np
arr = np.array(42)
print(arr)

42


In [11]:
# 1-D array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
# 2-D array 
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
# 3-D array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [99]:
# multidimensional array 
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(a)
print(b)
print(c)
print(d)

0
1
2
3
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
--------shape--------
()
(5,)
(2, 3)
(2, 2, 3)


In [ ]:
item 5: Array Indexing

In [45]:
import numpy as np
arr = np.array([1,2,3,4]) # one dimensional array 
print(arr[0]) # get the first element
print(arr[1]) # get the second element
print(arr[0] + arr[3]) # the output should be 5
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # two dimensional array
# access 9 
print(arr[1,3])
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])# three dimensional array
print(arr[0,1,1]) # access 5

1
2
5
9
5


In [ ]:
 item 6: Array Slicing 

In [77]:
import numpy as np
arr = np.array([1,2,3,4,5,6.7])
print(arr[1:5])
# negative slicing
print(arr[0:])

[2. 3. 4. 5.]
[1.  2.  3.  4.  5.  6.7]


In [ ]:
item 7: Data Types 

In [79]:
# integers 
import numpy as np
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [81]:
# strings
import numpy as np
arr = np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [83]:
# array with datatype string
import numpy as np
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [85]:
# array with 4 byte integers
import numpy as np
arr = np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [87]:
# convert data type that if float f into integer i 
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [89]:
# convert data type integer into bool b
import numpy as np
arr = np.array([1,0,3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
item 8:
numpy copy vs view 

In [91]:
# copy example 
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr) # old array 
print(x) # new array 

[42  2  3  4  5]
[1 2 3 4 5]


In [93]:
# view example 
# if I change in arr it will manipulate x 
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# use base to check if the array owns its data

In [97]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
item 9: numpy array shape 

In [103]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
e = np.array([1,2,3,4], ndmin=5)
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape) # 5 dimensional array 

()
(5,)
(2, 3)
(2, 2, 3)
(1, 1, 1, 1, 4)


In [ ]:
item 10: numpy array reshape

In [105]:
# reshape from 1-d to 2-d
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [107]:
# reshape from 1-d to 3-d 
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2) # 2 outer array with 3 inner array and 2 elements in each of inner aray 
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [109]:
# check if the returned array is a copy or a view
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [111]:
# cannot pass -1 to more than one dimension
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [113]:
# flattening the arrays
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
item 11:
Array Iterating

In [1]:
# 1-D array 
import numpy as np
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [3]:
# 2-D array through each row
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [7]:
# 2-D array though scalars
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [9]:
# 3-d array rows
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [11]:
# 3-d array with scalars
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for x in y:
            print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [13]:
# iteration with nditer()
import numpy as np
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [15]:
# iterating array with different data types
import numpy as np
arr = np.array([1,2,3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [17]:
# iterating with different step size
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [19]:
# enumerated iteration using ndenumerate
import numpy as np
arr = np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [21]:
## enumerated iteration using ndenumerate in 2d arrays
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
item 12:
Numpy Array Join

In [25]:
# Join two arrays 
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [27]:
# Join two dimensional array with axis=1
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [29]:
# Join arrays using stack functions
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [31]:
# Join arrays using hstack() function along rows 
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [33]:
# join array using vstack function
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)


[[1 2 3]
 [4 5 6]]


In [35]:
# dstack() along height
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
item 13:
split

In [37]:
# split the array in three parts
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [39]:
# split the array in four parts
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [41]:
# split the array and print it 
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [43]:
# split the array in three 2-D arrays 
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [47]:
# split the 2-D array into three 2-D arrays
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [49]:
# split the 2-D array into three 2-D arrays along rows
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [51]:
# hsplit() method to split the 2-D array into three 2-D arrays along rows
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
item 13:
Array Search

In [1]:
# using where 
# Find the indexes where the value is 4
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [3]:
# using where 
# Find the indexes where the value are even
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [5]:
# using where 
# find the indexes where the value are odd
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [7]:
# using searchsorted
# Find the indexes where the value 7 should be inserted
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7)
print(x)

1


In [9]:
# using searchsorted
# find the indexes where the value 7 should be inserted, starting from the right
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [11]:
# using searchsorted
# Find the indexes where the values 2,4 and 6 should be inserted
import numpy as np
arr = np.array([1,3,5,7])
x = np.searchsorted(arr, [2,4,6])
print(x)

[1 2 3]


In [ ]:
item 14:
Sorting Arrays

In [13]:
# sort() 
# sort the array
import numpy as np
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [15]:
# sort the array alphabetically
import numpy as np
arr = np.array(['banana', 'cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [17]:
# sort
# sort a boolean array 
import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [19]:
# sort
# sort 2-D array 
import numpy as np
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
item 14:
Array Filter

In [21]:
# Create and array from the elements on index 0 and  2:
import numpy as np
arr = np.array([41,42,43,33])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [23]:
# create a filter array that will return only values higher than 42:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = []
for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [25]:
# create a filter array that will return only even elements from the original array
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
filter_arr = []
for element in arr:
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [27]:
# create a filter array that will only return only values higher than 42:
import numpy as np
arr = np.array([41,42,43,44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [29]:
# create a filter array that will return only even elements from the original array
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
filter_arr = arr %2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
